import { StyleSheet } from 'react-native';
import { height, width } from '../../../utils/dimensions';
import { appColors } from '../../../utils/appColors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: appColors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: height(20),
  },
  loadingSpinnerContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: height(2),
    backgroundColor: appColors.favorite + '10',
  },
  loadingText: {
    fontSize: 16,
    fontWeight: '500',
    color: appColors.textMuted,
    marginTop: height(2),
  },
  errorBanner: {
    backgroundColor: '#7f1d1d80',
    borderLeftWidth: 4,
    borderLeftColor: appColors.red,
    marginHorizontal: width(4),
    marginTop: height(1),
    marginBottom: height(1),
    borderRadius: 8,
    overflow: 'hidden',
  },
  errorBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: width(4),
  },
  errorBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: width(2),
  },
  errorIconContainer: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorIcon: {
    fontSize: 20,
    color: '#fca5a5',
  },
  errorText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: '#fca5a5',
  },
  errorCloseButton: {
    padding: width(1),
  },
  headerContainer: {
    paddingTop: height(2),
    paddingBottom: height(2),
    paddingHorizontal: width(6),
  },
  headerContent: {
    alignItems: 'center',
    marginBottom: height(3),
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: width(2),
    paddingHorizontal: width(4),
    paddingVertical: height(1),
    borderRadius: 999,
    backgroundColor: appColors.favorite + '20',
    borderWidth: 1,
    borderColor: appColors.favorite + '30',
    marginBottom: height(2),
  },
  headerBadgeText: {
    fontSize: 14,
    fontWeight: '500',
    color: appColors.favorite,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: appColors.textPrimary,
    marginBottom: height(1),
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: 16,
    color: appColors.textMuted,
    textAlign: 'center',
    paddingHorizontal: width(4),
    lineHeight: 22,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: width(3),
    marginTop: height(2),
  },
  statCard: {
    flex: 1,
    backgroundColor: appColors.surface,
    borderRadius: 12,
    padding: width(3.5),
    flexDirection: 'row',
    alignItems: 'center',
    gap: width(2.5),
    borderWidth: 1,
    borderColor: appColors.surface,
  },
  statIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statIconRed: {
    backgroundColor: appColors.favorite + '20',
  },
  statIconGreen: {
    backgroundColor: appColors.green + '20',
  },
  statIconAmber: {
    backgroundColor: '#f59e0b20',
  },
  statContent: {
    flex: 1,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: appColors.textPrimary,
  },
  statLabel: {
    fontSize: 12,
    color: appColors.textMuted,
    marginTop: 2,
  },
  listContainer: {
    flex: 1,
  },
  contentContainer: {
    paddingTop: height(1),
    paddingHorizontal: width(6),
    paddingBottom: height(4),
  },
  emptyState: {
    marginTop: height(8),
    marginBottom: height(8),
    alignItems: 'center',
    paddingHorizontal: width(6),
  },
  emptyIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: height(3),
    position: 'relative',
  },
  emptyIconBackground: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: appColors.favorite + '20',
    opacity: 0.5,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: appColors.textPrimary,
    marginBottom: height(1),
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: appColors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: height(4),
    paddingHorizontal: width(4),
  },
  emptyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: width(2),
    paddingHorizontal: width(6),
    paddingVertical: height(1.5),
    backgroundColor: appColors.favorite,
    borderRadius: 12,
    shadowColor: appColors.favorite,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  emptyButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: appColors.white,
  },
  card: {
    backgroundColor: appColors.surface,
    borderRadius: 16,
    paddingVertical: height(1.5),
    paddingHorizontal: width(4),
    marginBottom: height(1.5),
  },
  title: {
    fontSize: 15,
    fontWeight: '600',
    color: appColors.textPrimary,
    marginBottom: height(1),
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: 12,
    color: appColors.textMuted,
  },
  value: {
    marginTop: 4,
    fontSize: 15,
    fontWeight: '600',
    color: appColors.textSecondary,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: appColors.surface,
    borderWidth: 1,
    borderColor: appColors.outline,
  },
  badgeText: {
    fontSize: 11,
    color: appColors.textSecondary,
  },
  statusText: {
    marginTop: height(1),
    fontSize: 13,
    color: appColors.textMuted,
  },
});
