const screenNames = {
  welcome: 'Welcome',
  authentication: 'Authentication',
  home: 'Home',
  forgetPassword: 'ForgetPassword',
  adminHome: 'AdminHome',
  profile: 'Profile',
  editProfile: 'EditProfile',
  helpSupport: 'HelpSupport',
  faqs: 'Faqs',
  clientHome: 'ClientHome',
  changePassword: 'ChangePassword',
  notifications: 'Notifications',
  addAuctionItem: 'AddAuctionItem',
  admiHome: 'AdminHome',
  adminAuctionItems: 'AdminAuctionItems',
  adminHomeTab: 'AdminHomeTab',
  myBids: 'MyBids',
  favorites: 'Favorites',
  clientHomeTab: 'ClientHomeTab',
  privacyPolicies: 'PrivacyPolicies',
  itemDetails: 'ItemDetails',
  userDetails: 'UserDetails',
  chatScreen: 'ChatScreen',
  brokerHomeTab: 'BrokerHomeTab',
  brokerHome: 'BrokerHome',
  brokerAuctionItems: 'BrokerAuctionItems',
  adminChats: 'AdminChats',
  adminUsers: 'AdminUsers',
  adminInvoices: 'AdminInvoices',
  brokerChats: 'BrokerChats',
  brokerInvoices: 'BrokerInvoices',
} as const;

export default screenNames;
